nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: Schoox Symfony 7.1 Course CRUD API!
            version: 1.0.0
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc$)
